### ISSUE TITLE
Downloading image or file?

### ISSUE THREAD

**Issue by ttuygun** [RahulKatariya/Reactofire#15]
Are there any implementation in Restofire or will we use Alamofire instead?

**Comment by rahul0x24** [comment]
Restore doesn't support download or uploading of files. It is in the plan going ahead and also support CoreData but due to very limited time and I being the only contributor, they are going to take some time.

Right now you can use Alamofire.

Note: You don't have to explicitly clone Alamofire. It is already linked with Restofire.

**Comment by rahul0x24** [comment]
Added Downloadable Support in v3
