### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [RahulKatariya/Reactofire#8]
`CocoaPods` and `Carthage` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by rahul0x24** [comment]
Good work at the template 👍🏻.

I tried a method of adding it manually by git submodule but it doesn't seem to work as it depends on Alamofire. Give me a little more time or I will be happy to review a pull request if you have a manual installation guide for Restofire.

**Comment by lfarah** [comment]
What about something like this?

#### Manually
1. Install [Alamofire](https://github.com/Alamofire/Alamofire)
2. Download and drop `YourLibrary.swift` in your project.  
3. Congratulations!

**Comment by rahul0x24** [comment]
This should work if there is only single swift file. But in my case there is a framework which i should create and attach to release.

Appreciate your efforts. Just give me a little more time to resolve this.

**Comment by rahul0x24** [comment]
Resolved 👍🏻. Let me know if there is any issue.

**Comment by lfarah** [comment]
@RahulKatariya your tutorial is really good and explanatory. What happens if the user just drags and drops the `/Sources` folder?

**Comment by rahul0x24** [comment]
User can install Restore by dragging and dropping the `/Sources` folder but it is not a recommended way because 
- The source files can conflict with your project files in naming conventions. If you don't have any dependency manager then you must be installing Alamofire by same approach which means more complexity. 
- It is difficult to stay up to date to new versions getting released.

I would recommend adding it as a Framework and use Restofire as a seperate module.

**Comment by lfarah** [comment]
Makes total sense!
